name: canid_phylogenomics
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - biopython>=1.79
  - pandas>=1.3
  - mafft>=7.490
  - hyphy>=2.5.47
  - snakemake-minimal>=7.0
  - numpy
